# NumPy for AI/ML – Conceptual & Technical Assessment
**Student Name:** Venkata Ajay Kumar Bodavula  
**File Name:** Ajay_numpy.ipynb

## Section A – Conceptual Understanding
### A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons.
NumPy arrays store elements in a single continuous block of memory with fixed data types, allowing your CPU to perform operations on whole chunks at once using SIMD instructions. Python lists store pointers scattered around memory with dynamic types, which creates a lot of memory lookup overhead during math tasks.

### A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?
Vectorization lets you run operations across an entire array without writing explicit Python `for` loops. It pushes the heavy lifting down to optimized C code, making computations run significantly faster and cleaner on large datasets.

### A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.
`A * B` multiplies matching positions in two arrays, which is useful in neural networks for applying weight masks or element-wise activation drops. `A @ B` performs actual matrix multiplication, which is what we use in neural networks to pass inputs through layer weights ($XW + b$).

### A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.
Broadcasting allows NumPy to work with arrays of different shapes without manually making copies of data. Two shapes are compatible if their dimensions match, or if one of the dimensions is equal to 1.

### A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?
`flatten()` always makes a completely new copy of the array in memory, while `ravel()` just gives you a 1D view of the original memory whenever possible. In high-memory tasks like image processing, `ravel()` is preferred because it saves RAM.

### A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.
`axis=0` operates vertically down columns (collapsing rows), while `axis=1` operates horizontally across rows (collapsing columns). For instance, given a 2x2 matrix `[[1, 2], [3, 4]]`, `np.sum(axis=0)` gives `[4, 6]`, and `np.sum(axis=1)` gives `[3, 7]`.

### A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.
When features have vastly different scales, machine learning models struggle to converge or end up heavily biased toward larger numbers. Normalization squeezes values into a fixed [0, 1] range, while standardization shifts values to have a mean of 0 and standard deviation of 1.

### A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN?
Standard `np.mean()` will break and return `NaN` if even one value in the data is missing. Functions like `np.nanmean()` automatically filter out `NaN` values and compute the average using only valid numbers.

### A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.
A batch of images adds a dataset size dimension to the standard 3D image format `(height, width, channels)`. For 64 RGB images sized 128x128, the exact tensor shape is `(64, 128, 128, 3)`.

### A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).
Fixing a random seed with `np.random.default_rng(seed)` ensures that pseudo-random steps—like dataset splitting or weight initialization—produce the exact same results every time you run the code.

## Section B – Predict the Output

### B1. Predict the exact output and/or resulting shape. Justify in one sentence.




In [9]:

a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

# predicted Output: (3, 3)

(3, 3)


Justification: Array a (shape 3,) and array b (shape 3, 1) broadcast across each other to make a 3x3 matrix.

### B2. Predict the output and/or shape.



In [10]:
x = np.arange(1, 7).reshape(2, 3)

print(x[:, 1])

##predicted Output: [2, 5]

[2 5]


Justification: The slice takes every row from the matrix but grabs only the elements in index 1 column.

### B3. Predict the output and/or shape.




In [11]:
arr = np.array([5, 10, 15, 20, 25])

print(arr[arr % 10 == 0])

##predicted Output: [10, 20]


[10 20]


Justification: The boolean mask checks for remainder zero when divided by 10 and filters out everything else.


### B4. Predict the output and/or shape.




In [12]:
m = np.array([[1, 2], [3, 4]])

print(m.T @ m)

##predicted Output:
#[[10 14]
# [14 20]]

[[10 14]
 [14 20]]


Justification: It transposes matrix m to [[1, 3], [2, 4]] and multiplies it with the original m matrix.

### B5. Predict the output and/or shape.



In [13]:
data = np.array([1, 2, np.nan, 4])

print(np.mean(data), np.nanmean(data))

##predictedOutput: nan 2.3333333333333335

nan 2.3333333333333335


Justification: Regular np.mean turns to nan because of missing data, but np.nanmean skips the missing value and averages the rest.


### B6. Predict the output and/or shape.





In [ ]:
x = np.array([10, 20, 30])

y = np.where(x > 15, 1, 0)

print(y)

## predicted Output: [0 1 1]

[0 1 1]


Justification: np.where checks if numbers are above 15, replacing matching values with 1 and others with 0.


### B7. Predict the output and/or shape.



In [15]:
a = np.zeros((3, 4))

print(a.ndim, a.size)

## predictedOutput: 2 12

2 12


Justification: ndim gives the number of dimensions (2D), while size gives the total count of elements (3 * 4 = 12).


### B8. Predict the output and/or shape.



In [17]:
arr = np.arange(1, 13).reshape(3, 4)

print(arr[::-1, ::-1])

##predicted Output:
#[[12 11 10  9]
 #[ 8  7  6  5]
 #[4  3  2  1]]
 

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


 Justification: Using ::-1 on both axes flips the entire matrix upside down and left to right.


## Section C (Coding / Implementation)
### C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40).




In [1]:
import numpy as np
scores = np.array([35, 45, 60, 28, 75, 39, 50])

result = np.where(scores >= 40, "P", "F")

print(result)

['F' 'P' 'P' 'F' 'P' 'F' 'P']


**Explanation:** `np.where()` checks each score and gives `P` for scores 40 or above and `F` for scores below 40.

### C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.


In [2]:
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


**Explanation:** The function calculates the mean and standard deviation, then standardizes each value using `(x - mean) / std`.

### C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.


In [3]:
batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

combined = np.vstack((batch1, batch2))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


**Explanation:** `np.vstack()` joins the two arrays one below the other because both arrays have the same number of columns.

### C4. Given `X` with shape `(100, 5)`, compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.


In [4]:
X = np.random.default_rng(42).normal(size=(100, 5))

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print("Mean shape:", mean.shape)
print("Standard deviation shape:", std.shape)
print("Standardized shape:", X_standardized.shape)

Mean shape: (5,)
Standard deviation shape: (5,)
Standardized shape: (100, 5)


**Explanation:** `axis=0` calculates the mean and standard deviation for each column, and NumPy uses broadcasting to standardize all the values at once.

### C5. Implement `y_pred = X @ w + b` for a feature matrix `X`, weight vector `w` and bias `b`. Then compute MSE using `y_true`.


In [5]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([2, 1])
b = 1

y_true = np.array([5, 8, 11])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [ 5  8 11]
MSE: 0.0


**Explanation:** `X @ w + b` calculates the predicted values, and MSE measures the average squared difference between the predicted and true values.

### C6. Using `np.random.default_rng()` with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.


In [6]:
rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))

print("Shape:", data1.shape)
print("Same results:", np.array_equal(data1, data2))

Shape: (10, 3)
Same results: True


**Explanation:** A fixed seed makes the random values repeatable, so using the same seed gives the same results again.

### C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.


In [7]:
image = np.array([[0, 50, 100],
                  [150, 200, 255]])

normalized = (image - np.min(image)) / (np.max(image) - np.min(image))

print(normalized)

[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]


**Explanation:** Min-max normalization changes the smallest value to 0 and the largest value to 1 using `(x - min) / (max - min)`.

### C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

In [8]:
images = np.random.default_rng(42).integers(
    0, 256, size=(4, 28, 28, 3)
)

average = np.mean(images, axis=(1, 2, 3))

print("Average values:", average)
print("Shape:", average.shape)

Average values: [127.56505102 126.25212585 125.75722789 126.9914966 ]
Shape: (4,)


**Explanation:** axis=(1, 2, 3) averages the height, width, and RGB channel dimensions while keeping the 4 images separate, so the result has one average value for each image.

## Section D (Applied / Scenario-Based Problems)

##### D1. Data Preprocessing Pipeline [8 marks]
- You are given a raw 1D or 2D NumPy array containing NaN values.
- Describe, step by step, the NumPy operations you would apply to:
- (a) detect missing values,
- (b) handle them appropriately and justify your strategy, and
- (c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

#### Explanation:

#### (a) Detecting Missing Values
To start off, we need to inspect the array for any absent data points. Using `np.isnan()`, we can locate missing values across the dataset:
- `np.isnan(data)` yields a boolean mask with `True` wherever a `NaN` exists.
- `np.sum(np.isnan(data))` counts the exact number of missing entries in the array.

#### (b) Handling Missing Values
Before feeding this data into a model, those blank entries need to be filled. 

A common strategy is imputing missing values using their respective column averages. We use `np.nanmean()` for this step since it computes averages while skipping `NaN` entries.

This strategy works well when missing data is sparse because:
- It preserves the rest of the valid data points in that sample.
- It prevents us from dropping entire rows and losing useful information.

#### (c) Standardizing the Cleaned Dataset
Once the missing entries are imputed, we scale the features using z-score standardization via the formula:

`z = (x - mean) / standard_deviation`

When working with 2D matrices, we set `axis=0` so the mean and standard deviation are calculated down each column individually.

This transformation ensures each feature ends up with:
- A mean of 0
- A standard deviation of 1

Rescaling features to a shared baseline keeps larger number ranges from dominating model training and helps optimization algorithms converge smoothly.

In [20]:
data = np.array([
    [10, 20, 30],
    [15, np.nan, 35],
    [20, 25, np.nan],
    [25, 30, 45]
])

# (a) Detect missing values
missing = np.isnan(data)

print("Missing value mask:")
print(missing)

print("Total missing values:", np.sum(missing))

# (b) Handle NaN values using column-wise mean
column_means = np.nanmean(data, axis=0)

# Replace NaN values with column means
clean_data = np.where(missing, column_means, data)

print("\nColumn means:")
print(column_means)

print("\nClean data:")
print(clean_data)

# (c) Standardize the clean data
mean = np.mean(clean_data, axis=0)
std = np.std(clean_data, axis=0)

standardized_data = (clean_data - mean) / std

print("\nStandardized data:")
print(np.round(standardized_data, 2))

print("\nMean after standardization:")
print(np.round(np.mean(standardized_data, axis=0), 2))

print("\nStandard deviation after standardization:")
print(np.round(np.std(standardized_data, axis=0), 2))

Missing value mask:
[[False False False]
 [False  True False]
 [False False  True]
 [False False False]]
Total missing values: 2

Column means:
[17.5        25.         36.66666667]

Clean data:
[[10.         20.         30.        ]
 [15.         25.         35.        ]
 [20.         25.         36.66666667]
 [25.         30.         45.        ]]

Standardized data:
[[-1.34 -1.41 -1.23]
 [-0.45  0.   -0.31]
 [ 0.45  0.    0.  ]
 [ 1.34  1.41  1.54]]

Mean after standardization:
[0. 0. 0.]

Standard deviation after standardization:
[1. 1. 1.]


### D2. Image Batch Processing & Average Image Calculation
##### RGB Image Shapes

| Feature | Single RGB Image | Batch of RGB Images |
|---|---|---|
| Number of dimensions | 3D | 4D |
| Shape | `(height, width, channels)` | `(number_of_images, height, width, channels)` |
| Example | `(28, 28, 3)` | `(10, 28, 28, 3)` |
| Number of images | `1` | `10` |

##### Meaning of the Dimensions

| Dimension | Single Image | Batch |
|---|---|---|
| First dimension | Height | Number of images |
| Second dimension | Width | Height |
| Third dimension | RGB channels | Width |
| Fourth dimension | Not present | RGB channels |

##### Difference

A single RGB image has **3 dimensions**, while a batch of RGB images has **4 dimensions**.

- Single image → `(28, 28, 3)`
- Batch of 10 images → `(10, 28, 28, 3)`

The extra first dimension in the batch represents the **number of images**.

In [21]:
# Single RGB image
image = np.random.randint(0, 256, size=(28, 28, 3))

# Batch of 10 RGB images
images = np.random.randint(0, 256, size=(10, 28, 28, 3))

print("Single image shape:", image.shape)
print("Batch of images shape:", images.shape)

Single image shape: (28, 28, 3)
Batch of images shape: (10, 28, 28, 3)


2.Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.


#### Creating a Dummy Batch of Images

A dummy batch of 16 RGB images, where each image has a size of 64 × 64 pixels, can be created using NumPy.

The shape of the batch is:

(16, 64, 64, 3)

| Dimension | Meaning |
|---|---|
| `16` | Number of images |
| `64` | Image height |
| `64` | Image width |
| `3` | RGB color channels |

We use np.random.randint(0, 256) to generate random pixel values between **0 and 255**.

For an RGB image:
- `0` represents the minimum pixel intensity.
- `255` represents the maximum pixel intensity.
- `3` represents the Red, Green, and Blue channels.

Therefore, the resulting NumPy array represents **16 random RGB images**, each of size **64 × 64**.

In [22]:
images = np.random.randint(0, 256, size=(16, 64, 64, 3))

print("Shape:", images.shape)

Shape: (16, 64, 64, 3)


3.Compute the average image of the batch, meaning the element-wise mean across all 16 images.

### Average Image of a Batch

The batch contains **16 RGB images**, each with shape `(64, 64, 3)`.

The complete batch has the shape:

`(16, 64, 64, 3)`

To calculate the average image, we use:

`np.mean(images, axis=0)`

We use `axis=0` because we want to calculate the mean across the 16 images, while keeping the height, width, and RGB channels unchanged.

The resulting average image has the shape:

`(64, 64, 3)`

Each pixel in the average image represents the average pixel value at the same position across all 16 images.

In [23]:

images = np.random.randint(0, 256, size=(16, 64, 64, 3))

average_image = np.mean(images, axis=0)

print("Original batch shape:", images.shape)
print("Average image shape:", average_image.shape)

Original batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


4.State the shape of your result and explain why.


The original batch has the shape:

`(16, 64, 64, 3)`

The average image is calculated using:

`np.mean(images, axis=0)`

The result has the shape:

`(64, 64, 3)`

##### Reason

We use `axis=0` because the first dimension represents the **16 images**.

By taking the mean along `axis=0`, the 16 images are averaged pixel-by-pixel.

The remaining dimensions are:

- `64` → Height
- `64` → Width
- `3` → RGB channels

Therefore, the `16` dimension is removed, and we get one average RGB image with shape:

`(64, 64, 3)`



### D3. Debug the Model Code

The following code contains more than one bug:

```python
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  

w = np.array([0.5, 1.0, 0.2])  

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)
```
#### Tasks
1. Identify every bug.
2. Explain, in terms of **shapes**, why each bug is a problem.
3. Explain how **operator precedence** affects the MSE calculation.
4. Rewrite the **corrected code**.

#### 1. Identify Every Bug

There are **two main bugs** in the given code.

##### Bug 1: Incorrect Shape of `w`

The shape of `X` is `(3, 2)`, which means `X` has **3 samples and 2 features**.

But `w` is:

`w = np.array([0.5, 1.0, 0.2])`

Its shape is `(3,)`.

This is incorrect because `w` must contain **one weight for each feature**.

Therefore, `w` should have shape `(2,)`:

`w = np.array([0.5, 1.0])`

##### Bug 2: Incorrect MSE Calculation

The given expression is:

`mse = np.mean(y_true - y_pred ** 2)`

This is not the correct Mean Squared Error formula.

The correct expression is:

`mse = np.mean((y_true - y_pred) ** 2)`

The error between the actual and predicted values must be calculated first, and then the error should be squared.

#### 2. Explain Using Shapes Why Each Bug Is a Problem

The shape of `X` is:

`X.shape = (3, 2)`

This means:

- `3` → number of samples
- `2` → number of features

Therefore, the weight vector `w` must have **2 values**, one for each feature.

The given weight vector is:

`w.shape = (3,)`

This is incorrect because it contains 3 weights while `X` has only 2 features.

The correct shape is:

`w.shape = (2,)`

Then the matrix multiplication works as:

`(3, 2) @ (2,) → (3,)`

So, `y_pred` will have shape `(3,)`, which matches the shape of `y_true`.

`y_true.shape = (3,)`

Therefore, the corrected shapes are:

| Variable | Shape |
|---|---|
| `X` | `(3, 2)` |
| `w` | `(2,)` |
| `X @ w` | `(3,)` |
| `y_pred` | `(3,)` |
| `y_true` | `(3,)` |

The second bug is the MSE calculation. It is not a shape problem, because `y_true` and `y_pred` have matching shapes. The problem is that the expression does not calculate the squared error correctly.

#### 3. Explain How Operator Precedence Affects the MSE Calculation

The incorrect expression is:

`mse = np.mean(y_true - y_pred ** 2)`

In Python, the power operator `**` has **higher precedence** than the subtraction operator `-`.

Therefore, Python evaluates the expression as:

`y_true - (y_pred ** 2)`

This means only `y_pred` is squared, which is **not** the correct MSE calculation.

The correct MSE formula is:

`MSE = mean((y_true - y_pred)²)`

Therefore, we must use parentheses:

`mse = np.mean((y_true - y_pred) ** 2)`
The parentheses ensure that:

1. `y_true - y_pred` is calculated first.
2. The resulting error is squared.
3. The mean of the squared errors is calculated.

Hence, parentheses are necessary to calculate MSE correctly.

#### 4.Correct code

In [24]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("y_pred:", y_pred)
print("MSE:", mse)

y_pred: [4.5 6.  7.5]
MSE: 244.16666666666666


### Section E – Bonus / Challenge

#### E1. Per-Column Min–Max Normalization
Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.



#### Explanation:
To scale each feature independently into the $[0, 1]$ range, we apply min-max normalization across individual columns using the formula:

$$\text{X\_norm} = \frac{X - \text{min}(X, \text{axis}=0)}{\text{max}(X, \text{axis}=0) - \text{min}(X, \text{axis}=0)}$$

- Specifying `axis=0` calculates the minimum and maximum values along each column (feature) rather than across the entire matrix.
- NumPy's broadcasting automatically aligns these column-wise 1D min/max results with the 2D matrix shape, applying the operation across all rows in a single vectorized step without writing `for` loops.

In [25]:
import numpy as np

# Sample 2D feature matrix (3 samples, 2 features)
X = np.array([[10.0, 100.0], 
              [20.0, 200.0], 
              [30.0, 150.0]])

# Per-column min-max normalization using broadcasting
X_norm = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

print("Normalized Matrix:\n", X_norm)
# Explanation: Computes column-wise minimum and maximum along axis=0 to scale each feature into [0, 1] without loops.

Normalized Matrix:
 [[0.  0. ]
 [0.5 1. ]
 [1.  0.5]]


#### E2. Three-Level Score Classification
Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).
Hint: You may need to nest or combine np.where() calls.

#### Explanation:
To categorize continuous scores into three distinct performance tiers without using explicit Python `for` loops or `if/else` conditions, we use nested `np.where()` calls:

- The outer `np.where()` checks if a score is below 40. If true, it assigns `'Fail'`.
- If false, execution passes to the inner `np.where()`, which checks if the score is $\le 70$. If true, it assigns `'Average'`.
- Anything remaining above 70 defaults to `'Excellent'`.

This approach processes the entire array in a single vectorized operation.

In [26]:
import numpy as np

# Sample 1D array of student exam scores
scores = np.array([25, 40, 68, 71, 90, 39])

# Single vectorized expression using nested np.where()
categories = np.where(scores < 40, 'Fail', 
             np.where(scores <= 70, 'Average', 'Excellent'))

print("Scores:", scores)
print("Classifications:", categories)
# Explanation: Classifies scores into Fail, Average, or Excellent using nested np.where calls without explicit loops.

Scores: [25 40 68 71 90 39]
Classifications: ['Fail' 'Average' 'Average' 'Excellent' 'Excellent' 'Fail']
