In [1]:
#1.Create a NumPy array containing numbers from 10 to 100 with a step of 10.
import numpy as np
arr_1 = np.arange(10, 101, 10)
print("1:", arr_1)


1: [ 10  20  30  40  50  60  70  80  90 100]


In [2]:
#2. Create a `3 x 4` array of zeros.
import numpy as np
arr_zeros = np.zeros((3, 4))
print("2:\n", arr_zeros)

2:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#3. Create an array and print its `ndim`, `shape`, `size`, and `dtype`.
import numpy as np
arr_3 = np.array([[1, 2, 3], [4, 5, 6]])
print("3:")
print("ndim:", arr_3.ndim)
print("shape:", arr_3.shape)
print("size:", arr_3.size)
print("dtype:", arr_3.dtype)

3:
ndim: 2
shape: (2, 3)
size: 6
dtype: int64


In [4]:
#4. Extract the last element from a 1D array.
import numpy as np
arr_1d = np.array([10, 20, 30, 40, 50])
print("4:", arr_1d[-1])

4: 50


In [5]:
# 5. Select first two columns of a 2D array
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("5:\n", arr_2d[:, :2])

5:
 [[1 2]
 [4 5]
 [7 8]]


In [6]:
# 6. Reshape 12 numbers into a 3x4 matrix
import numpy as np
arr_12 = np.arange(12).reshape((3, 4))
print("6:\n", arr_12)

6:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# 7. Transpose a 2x3 matrix
import numpy as np
matrix_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print("7:\n", matrix_2x3.T)

7:
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
# 8. Multiply every element by 5
import numpy as np
print("8:", arr_1d * 5)

8: [ 50 100 150 200 250]


In [9]:
# 9. Feature matrix X (5 samples, 3 features)
import numpy as np
np.random.seed(42)
X = np.random.randint(10, 100, size=(5, 3))
print("9 Shape:", X.shape)

9 Shape: (5, 3)


In [10]:
# 10. Mean of each feature across samples (axis=0)
import numpy as np
feature_means = X.mean(axis=0)
print("10 Feature Means:", feature_means)

10 Feature Means: [71.  46.6 56. ]


In [11]:
# 11. Filter rows where first feature > 50
import numpy as np
filtered_X = X[X[:, 0] > 50]
print("11 Filtered Rows:\n", filtered_X)

11 Filtered Rows:
 [[61 24 81]
 [70 30 92]
 [96 84 84]
 [97 33 12]]


In [12]:
# 12. Standardize every feature column (Z-score normalization)
import numpy as np
means = X.mean(axis=0)
stds = X.std(axis=0)
X_standardized = (X - means) / stds
print("12 Standardized X:\n", X_standardized)

12 Standardized X:
 [[-0.40811228 -0.98970615  0.68468743]
 [-0.04081123 -0.7269523   0.9859499 ]
 [ 1.02028069  1.6378323   0.76684992]
 [ 1.06109192 -0.59557538 -1.20504988]
 [-1.6324491   0.67440153 -1.23243738]]


In [13]:
# 13. Random matrix (10, 4) with fixed seed
import numpy as np
np.random.seed(123)
rand_matrix = np.random.rand(10, 4)
print("13 Shape:", rand_matrix.shape)

13 Shape: (10, 4)


In [14]:
# 14. Matrix-vector multiplication (X @ weights)
import numpy as np
weights = np.array([0.5, 0.2, 0.8])
predictions = X @ weights
print("14 Matrix Multiplication Output:\n", predictions)

14 Matrix Multiplication Output:
 [100.1 114.6 132.   64.7  36.7]


In [15]:
# 15. Add bias vector using broadcasting
import numpy as np
bias = np.array([1.0, 0.5, -0.5])
X_biased = X + bias
print("15 Broadcasted Addition:\n", X_biased)

15 Broadcasted Addition:
 [[62.  24.5 80.5]
 [71.  30.5 91.5]
 [97.  84.5 83.5]
 [98.  33.5 11.5]
 [32.  62.5 10.5]]


In [16]:
# 16. Mean Squared Error (MSE)
import numpy as np
y_true = np.array([2.5, 0.0, 2.1, 7.8])
y_pred = np.array([3.0, -0.5, 2.0, 7.2])
mse = np.mean((y_true - y_pred) ** 2)
print("16 MSE:", mse)

16 MSE: 0.21749999999999992


In [17]:
# 17. 28x28 grayscale image
import numpy as np
gray_img = np.zeros((28, 28), dtype=np.uint8)
print("17 Grayscale Image Shape:", gray_img.shape)

17 Grayscale Image Shape: (28, 28)


In [18]:
# 18. Batch of 64 RGB images (224x224)
import numpy as np
img_batch = np.zeros((64, 224, 224, 3), dtype=np.uint8)
print("18 Image Batch Shape:", img_batch.shape)

18 Image Batch Shape: (64, 224, 224, 3)


In [19]:
# 19. Array with NaN and NaN-safe mean
import numpy as np
nan_arr = np.array([10.0, 20.0, np.nan, 40.0])
print("19 NaN-safe Mean:", np.nanmean(nan_arr))

19 NaN-safe Mean: 23.333333333333332


In [ ]:
#20. Explain the difference between `A * B` and `A @ B` in your own words. for this 
A * B (Element-wise Multiplication)
Multiplies corresponding elements at the same position in both arrays item-by-item.
Both arrays must have identical or broadcastable shapes (e.g., [1, 2] * [3, 4] = [3, 8]).
A @ B (Matrix Multiplication)
Computes the standard linear algebra dot product between rows of A and columns of B. 
Requires the number of columns in A to match the number of rows in B (e.g..,(m * n) @ (n * p) --> (m * p))